server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : pokemon-service
          uri: http://localhost:8090
          predicates:
            - Path=/pokemon/**
        - id: pokedex-service
          uri: http://localhost:8091
          predicates:
            - Path=/pokedex/**
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka