server:
  port: 9090

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : pokemon-service
          uri: lb://POKEMON-SERVICE
          predicates:
            - Path=/pokemon/**
        - id: pokedex-service
          uri: lb://POKEDEX-SERVICE
          predicates:
            - Path=/pokedex/**